import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import logoImg from "../assets/Logo.svg";
import Image from "next/image";
import styles from "@/styles/pages/app.module.scss";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <div className={styles.Container}>
          <header className={styles.Header}>
            <Image
              src={logoImg.src}
              alt="Ignite Shop"
              width={logoImg.width}
              height={logoImg.height}
            />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
